development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
adapter: postgresql
encoding: unicode
pool: 5
database: d8r223cedq2q6v
username: kclazkexnooftl
password: PuK8R3p8MKuyS0bN0AaTtzwEP0
host: ec2-54-225-124-205.compute-1.amazonaws.com
port: 5432